# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pwgen


class Ui_MainWindow(object):

    def checked(self):
        
        final_combs = []
        settings = pwgen.Settings()

        IncLeet = self.IncludeLeetCheck.checkState()
        IncWL = self.IncludeWLCheck.checkState()
        IncComboPS = self.IncludeCombosCheck.checkState()
        IncNumsPre = self.IncludeNumsPreCheck.checkState()
        IncNumsSuff = self.IncludeNumsSufCheck.checkState()
        IncNumsInWL = self.IncludeNumsCheck.checkState()
        UseDefaultCharList = self.DefaultListCheck.checkState()
        customWord = self.CustomWordsText.toPlainText()
        prefixText = self.AddPrefixText.toPlainText()
        suffixText = self.AddSuffixText.toPlainText()
        customList = self.CustomListText.toPlainText()
        extendList = self.ExtendDefaultListText.toPlainText()
        prefixNumLen = self.PrefixNumLenCheck.value()
        suffixNumLen = self.SuffixNumLenCheck.value()
        MinComboLen = self.MinComboLenCheck.value()
        MaxComboLen = self.MaxComboLenCheck.value()

        if UseDefaultCharList == 2:
            chrs = 'abcdefghijklmnopqrstuvwxyz'
        elif IncNumsInWL:
            chrs = 'abcdefghijklmnopqrstuvwxyz0123456789' 
        elif customList != '':
            chrs = customList
        else:
            chrs = 'abcdefghijklmnopqrstuvwxyz' + extendList
        
        if prefixText != '':
            add_pre = 2
        else:
            add_pre = 0

        if suffixText != '':
            add_suf = 2
        else:
            add_suf = 0

        leet_combos = settings.LeetCombo(customWord, IncLeet)
        word_list_combos = settings.WordCombos(MinComboLen, MaxComboLen, chrs, IncWL)
        final_combs = leet_combos + word_list_combos
        prefix_combos = settings.AddPrefix(prefixText, final_combs, IncComboPS, add_pre)
        suffix_combos = settings.AddSuffix(suffixText, final_combs, IncComboPS, add_suf)
        final_combs += prefix_combos + suffix_combos
        prefixNumCombos = settings.AddNumPrefix(prefixNumLen, prefixNumLen, final_combs, IncNumsPre)
        suffixNumCombos = settings.AddNumSuffix(suffixNumLen, suffixNumLen, final_combs, IncNumsSuff)
        final_combs += prefixNumCombos + suffixNumCombos

        settings.WritePass(final_combs)

        print("Added Combinations")


    def setupUi(self, MainWindow):


        '''
        IncludeLeetCheck -
            CheckBox for including Leet combinations
        IncludeWLCheck -
            CheckBox for including a word list
        CustomWordsText -
            A text box for making combinations of a custom word
        AddPrefixText -
            A text box for adding a prefix before the combinations
        AddSuffixText -
            A text box for adding a suffix after the combinations
        IncludeCombosCheck -
            A check box for giving the option to add combinations of prefix
        IncludeNumsPreCheck -
            A check box for including numbers as prefix
        IncludeNumsSufCheck -
            A check box for including numbers as suffix
        PrefixNumLenCheck -
            A spin box for setting the length of numbers as the prefix
        SuffixNumLenCheck -
            A spin box for setting the length of numbers as the suffix
        IncludeNumsCheck -
            A check box for including numbers in the wordlist
        DefaultListCheck -
            A check box for using the default character list (abcdefghizjklmonpqrstuvqxyz)
        MinComboLenCheck -
            A spin box for setting the minimum length of combinations
        MaxComboLenCheck -
            A spin box for setting the maximum length of combinations
        CustomListText -
            A text box for making a custom character list
        ExtendDefaultListText -
            A text box for extending the default character list
        Generate -
            A button to make the combinations
        '''

        #QMainWindow setup
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(940, 577)
        MainWindow.setAutoFillBackground(True)


        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        
        #IncludeWLCheck settings
        self.IncludeWLCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.IncludeWLCheck.setGeometry(QtCore.QRect(40, 110, 16, 17))
        self.IncludeWLCheck.setText("")
        self.IncludeWLCheck.setChecked(False)
        self.IncludeWLCheck.setObjectName("IncludeWLCheck")


        #:eetCombinationsLabel settings
        self.LeetCombinationsLabel = QtWidgets.QLabel(self.centralwidget)
        self.LeetCombinationsLabel.setGeometry(QtCore.QRect(70, 80, 131, 21))
        self.LeetCombinationsLabel.setAutoFillBackground(True)
        self.LeetCombinationsLabel.setObjectName("LeetCombinationsLabel")


        #GenWordListLabel settings
        self.GenWordListLabel = QtWidgets.QLabel(self.centralwidget)
        self.GenWordListLabel.setGeometry(QtCore.QRect(70, 110, 111, 16))
        self.GenWordListLabel.setAutoFillBackground(True)
        self.GenWordListLabel.setObjectName("GenWordListLabel")


        #IncludeLeetCheck settings
        self.IncludeLeetCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.IncludeLeetCheck.setGeometry(QtCore.QRect(40, 80, 16, 17))
        self.IncludeLeetCheck.setText("")
        self.IncludeLeetCheck.setObjectName("IncludeLeetCheck")


        #GeneralSettingsLabel settings
        self.GenralSettingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.GenralSettingsLabel.setGeometry(QtCore.QRect(30, 30, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.GenralSettingsLabel.setFont(font)
        self.GenralSettingsLabel.setObjectName("GenralSettingsLabel")


        #PrefixSuffixSettignsLabel settings
        self.PrefixSuffixSettingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.PrefixSuffixSettingsLabel.setGeometry(QtCore.QRect(30, 200, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.PrefixSuffixSettingsLabel.setFont(font)
        self.PrefixSuffixSettingsLabel.setObjectName("PrefixSuffixSettingsLabel")


        #CustomWordsText settings
        self.CustomWordsText = QtWidgets.QTextEdit(self.centralwidget)
        self.CustomWordsText.setGeometry(QtCore.QRect(40, 140, 104, 31))
        self.CustomWordsText.setObjectName("CustomWordsText")


        #CustomWordLabel settings
        self.CustomWordsLabel = QtWidgets.QLabel(self.centralwidget)
        self.CustomWordsLabel.setGeometry(QtCore.QRect(160, 140, 231, 31))
        self.CustomWordsLabel.setObjectName("CustomWordsLabel")


        #AddPrefixText settings
        self.AddPrefixText = QtWidgets.QTextEdit(self.centralwidget)
        self.AddPrefixText.setGeometry(QtCore.QRect(40, 230, 104, 31))
        self.AddPrefixText.setObjectName("AddPrefixText")


        #AddSuffixText settings
        self.AddSuffixText = QtWidgets.QTextEdit(self.centralwidget)
        self.AddSuffixText.setGeometry(QtCore.QRect(40, 280, 104, 31))
        self.AddSuffixText.setObjectName("AddSuffixText")


        #IncludeCombosCheck settings
        self.IncludeCombosCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.IncludeCombosCheck.setGeometry(QtCore.QRect(40, 320, 16, 17))
        self.IncludeCombosCheck.setText("")
        self.IncludeCombosCheck.setChecked(False)
        self.IncludeCombosCheck.setObjectName("IncludeCombosCheck")


        #IncludeNumsPreCheck settings
        self.IncludeNumsPreCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.IncludeNumsPreCheck.setGeometry(QtCore.QRect(40, 350, 16, 17))
        self.IncludeNumsPreCheck.setText("")
        self.IncludeNumsPreCheck.setChecked(False)
        self.IncludeNumsPreCheck.setObjectName("IncludeNumsPreCheck")


        #AddPrefixLabel settings
        self.AddPrefixLabel = QtWidgets.QLabel(self.centralwidget)
        self.AddPrefixLabel.setGeometry(QtCore.QRect(170, 240, 61, 21))
        self.AddPrefixLabel.setObjectName("AddPrefixLabel")


        #AddSuffixLabel settings
        self.AddSuffixLabel = QtWidgets.QLabel(self.centralwidget)
        self.AddSuffixLabel.setGeometry(QtCore.QRect(170, 290, 71, 21))
        self.AddSuffixLabel.setObjectName("AddSuffixLabel")


        #IncludecombosLabel settings
        self.IncludeCombosLabel = QtWidgets.QLabel(self.centralwidget)
        self.IncludeCombosLabel.setGeometry(QtCore.QRect(80, 320, 211, 16))
        self.IncludeCombosLabel.setObjectName("IncludeCombosLabel")


        #IncludeNumsPreLabel settings
        self.IncludeNumsPreLabel = QtWidgets.QLabel(self.centralwidget)
        self.IncludeNumsPreLabel.setGeometry(QtCore.QRect(80, 346, 131, 20))
        self.IncludeNumsPreLabel.setObjectName("IncludeNumsPreLabel")


        #IncludeNumsSufCheck settings
        self.IncludeNumsSufCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.IncludeNumsSufCheck.setGeometry(QtCore.QRect(40, 380, 16, 17))
        self.IncludeNumsSufCheck.setText("")
        self.IncludeNumsSufCheck.setObjectName("IncludeNumsSufCheck")


        #IncludeNumsSufLabel settings
        self.IncludeNumsSufLabel = QtWidgets.QLabel(self.centralwidget)
        self.IncludeNumsSufLabel.setGeometry(QtCore.QRect(80, 380, 131, 20))
        self.IncludeNumsSufLabel.setObjectName("IncludeNumsSufLabel")

        
        #SuffixNumLenLabel settings
        self.SuffixNumLenLabel = QtWidgets.QLabel(self.centralwidget)
        self.SuffixNumLenLabel.setGeometry(QtCore.QRect(100, 460, 111, 20))
        self.SuffixNumLenLabel.setObjectName("SuffixNumLenLabel")


        #PrefixNumLenLabel settings
        self.PrefixNumLenLabel = QtWidgets.QLabel(self.centralwidget)
        self.PrefixNumLenLabel.setGeometry(QtCore.QRect(100, 420, 111, 20))
        self.PrefixNumLenLabel.setObjectName("PrefixNumLenLabel")


        #PrefixNumLenCheck settings
        self.PrefixNumLenCheck = QtWidgets.QSpinBox(self.centralwidget)
        self.PrefixNumLenCheck.setGeometry(QtCore.QRect(40, 420, 42, 22))
        self.PrefixNumLenCheck.setObjectName("PrefixNumLenCheck")


        #SuffixNumLenCheck
        self.SuffixNumLenCheck = QtWidgets.QSpinBox(self.centralwidget)
        self.SuffixNumLenCheck.setGeometry(QtCore.QRect(40, 460, 42, 22))
        self.SuffixNumLenCheck.setObjectName("SuffixNumLenCheck")


        #IncludeNumsCheck settings
        self.IncludeNumsCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.IncludeNumsCheck.setGeometry(QtCore.QRect(480, 80, 16, 17))
        self.IncludeNumsCheck.setText("")
        self.IncludeNumsCheck.setObjectName("IncludeNumsCheck")


        #MinComboLenCheck settings
        self.MinComboLenCheck = QtWidgets.QSpinBox(self.centralwidget)
        self.MinComboLenCheck.setGeometry(QtCore.QRect(480, 140, 42, 22))
        self.MinComboLenCheck.setObjectName("MinComboLenCheck")


        #MaccomvoLenLabel settings
        self.MaxComboLenLabel = QtWidgets.QLabel(self.centralwidget)
        self.MaxComboLenLabel.setGeometry(QtCore.QRect(540, 180, 101, 20))
        self.MaxComboLenLabel.setObjectName("MaxComboLenLabel")

        
        #ExtanddefaultListLabel settings
        self.ExtandDefaultListLabel = QtWidgets.QLabel(self.centralwidget)
        self.ExtandDefaultListLabel.setGeometry(QtCore.QRect(600, 259, 161, 31))
        self.ExtandDefaultListLabel.setObjectName("ExtandDefaultListLabel")


        #MinComboLenLabel settings
        self.MinComboLenLabel = QtWidgets.QLabel(self.centralwidget)
        self.MinComboLenLabel.setGeometry(QtCore.QRect(540, 140, 91, 20))
        self.MinComboLenLabel.setObjectName("MinComboLenLabel")


        #DefaultListLabel settings
        self.DefaultListLabel = QtWidgets.QLabel(self.centralwidget)
        self.DefaultListLabel.setGeometry(QtCore.QRect(510, 110, 161, 16))
        self.DefaultListLabel.setObjectName("DefaultListLabel")


        #CustomListLabel settings
        self.CustomListLabel = QtWidgets.QLabel(self.centralwidget)
        self.CustomListLabel.setGeometry(QtCore.QRect(600, 225, 271, 21))
        self.CustomListLabel.setObjectName("CustomListLabel")


        #WLSettingsLabel settings
        self.WLSettingsLabel = QtWidgets.QLabel(self.centralwidget)
        self.WLSettingsLabel.setGeometry(QtCore.QRect(470, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.WLSettingsLabel.setFont(font)
        self.WLSettingsLabel.setObjectName("WLSettingsLabel")

        
        #IncludeNUmsLabel settings
        self.IncludeNumsLabel = QtWidgets.QLabel(self.centralwidget)
        self.IncludeNumsLabel.setGeometry(QtCore.QRect(510, 80, 91, 16))
        self.IncludeNumsLabel.setObjectName("IncludeNumsLabel")


        #ExtendDefaultListText settings
        self.ExtendDefaultListText = QtWidgets.QTextEdit(self.centralwidget)
        self.ExtendDefaultListText.setGeometry(QtCore.QRect(480, 260, 101, 31))
        self.ExtendDefaultListText.setObjectName("ExtendDefaultListText")


        #CustomListText settings
        self.CustomListText = QtWidgets.QTextEdit(self.centralwidget)
        self.CustomListText.setGeometry(QtCore.QRect(480, 220, 101, 31))
        self.CustomListText.setObjectName("CustomListText")


        #DefaultListCheck settings
        self.DefaultListCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.DefaultListCheck.setGeometry(QtCore.QRect(480, 110, 16, 17))
        self.DefaultListCheck.setText("")
        self.DefaultListCheck.setObjectName("DefaultListCheck")


        #MaxComboLenCheck settings
        self.MaxComboLenCheck = QtWidgets.QSpinBox(self.centralwidget)
        self.MaxComboLenCheck.setGeometry(QtCore.QRect(480, 180, 42, 22))
        self.MaxComboLenCheck.setObjectName("MaxComboLenCheck")


        #GenrateButton settings
        self.GenerateButton = QtWidgets.QPushButton(self.centralwidget)
        self.GenerateButton.setGeometry(QtCore.QRect(420, 420, 151, 61))
        self.GenerateButton.setObjectName("GenerateButton")
        self.GenerateButton.clicked.connect(self.checked)


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        #Texts For all the labels
        self.LeetCombinationsLabel.setText(_translate("MainWindow", "Include Leet Combinatons"))
        self.GenWordListLabel.setText(_translate("MainWindow", "Generate a word list"))
        self.GenralSettingsLabel.setText(_translate("MainWindow", "General Settings"))
        self.PrefixSuffixSettingsLabel.setText(_translate("MainWindow", "Prefix and Suffix settings"))
        self.CustomWordsLabel.setText(_translate("MainWindow", "Custom word (Combinations for a custom word)"))
        self.AddPrefixLabel.setText(_translate("MainWindow", "Add Prefix"))
        self.AddSuffixLabel.setText(_translate("MainWindow", "Add Suffix"))
        self.IncludeCombosLabel.setText(_translate("MainWindow", "Add combinations of prefixes and suffixes"))
        self.IncludeNumsPreLabel.setText(_translate("MainWindow", "Add Numbers as prefix"))
        self.IncludeNumsSufLabel.setText(_translate("MainWindow", "Add Numbers as suffix"))
        self.SuffixNumLenLabel.setText(_translate("MainWindow", "Suffix Number Length"))
        self.PrefixNumLenLabel.setText(_translate("MainWindow", "Prefix Number Length"))
        self.MaxComboLenLabel.setText(_translate("MainWindow", "Max. Combo Length"))
        self.ExtandDefaultListLabel.setText(_translate("MainWindow", "Extend the default alphabet list"))
        self.MinComboLenLabel.setText(_translate("MainWindow", "Min. Combo length"))
        self.DefaultListLabel.setText(_translate("MainWindow", "Use default alphabet list (abc...)"))
        self.CustomListLabel.setText(_translate("MainWindow", "Custom Characters (Overrides the default alphabet list)"))
        self.WLSettingsLabel.setText(_translate("MainWindow", "Settings for word list"))
        self.IncludeNumsLabel.setText(_translate("MainWindow", "Include Numbers"))
        self.GenerateButton.setText(_translate("MainWindow", "Generate Combinations"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
